### PR TITLE
Fix for issues #47, #79, #84, and #102 Change related to #97

### PR DESCRIPTION
**Pull request by tubesoft**
Please see the page of each issue. Thank you!

### CODE REVIEW

**Comment by tubesoft** [comment]
Probably, according to what we have discussed regarding workflow, @wehooper might have to review first to approve my change.

**Comment by mdalmau** [comment]
Yes Wally should bring your fixed down to his local instance and once he’s tested he can comment, tag me and close the issues. Did you created a pull request already? Our internet is down so I’m working from my phone, sort of.

Typos and Autocorrections Courtesy of my iPhone and my Spanglish  Upbringing

On Mar 23, 2021, at 1:30 PM, Takatomo Inoue ***@***.***> wrote:

﻿
This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Probably, according to what we have discussed regarding workflow, @wehooper<https://github.com/wehooper> might have to review first to approve my change.

**Comment by tubesoft** [comment]
@mdalmau Yes, this thread is the pull request that I posted. I just talked about reviewing the code to @wehooper in the weekly meeting!

**Comment by mdalmau** [comment]
@wehooper once you test #79 I can merge this pull request! I'll watch for a closed issue.  Thanks!

**Comment by mdalmau** [comment]
@wehooper I recall from an email that you tested issue #79 but I don't want to merge this request until the issue  is closed. Thanks!

**Comment by mdalmau** [comment]
Merging pull request.  @randalldfloyd when you have a moment, could you update P5 carbon dev and P5 possum production?  Thanks!

**Comment by mdalmau** [comment]
Hey @randalldfloyd  .... I am trying to take stock on where Newton is on dev and prod updates as part of the Great Servers Move. I don't think carbon or possum was updated with this last merge in May.  When I check both, I don't see evidence of A-Z or the extra info in the pop-up notes (but I could also be checking the wrong mss for the notes.  @aewingate may know).

**Comment by aewingate** [comment]
I just checked by looking at ALCH00062 which has all four types of certainty. Carbon behaves differently from Possum, and neither are perfect. 
Carbon does have the notes inside of the pop-ups, but it also has it in-line with the text too, instead of just inside the pop-ups.
image

Possum has the notes in-line with the text and not inside of the pop-ups at all.
image

Also, in the pop-up for citations that have "high likelihood" of certainty (@cert="high"), it just says "Likelihood" instead of "High Likelihood"

**Comment by randalldfloyd** [comment]
@aewingate @mdalmau 
I just went through all of the instances and pulled the latest commits and then exported/reindexed from Xubmit in case any issues require indexing to fix.  

To my understanding, there are still just 2 sites that everyone is looking at, though there are more instances that haven't yet been utilized.  Here's what I *think* everyone is using, and both are up-to-date as of now:

- https://newton.dlib.indiana.edu/ = http://carbon.dlib.indiana.edu:8220/  (unreleased "production" on old server)
- http://possum.dlib.indiana.edu:8180/  (development/test on new server)

Additionally, we have http://possum.dlib.indiana.edu:8197/, which will be production at newton.dlib.indiana.edu when fully migrated.

**Pull request merged**
