### PR TITLE
Takatomo work nov2022

### PR DESCRIPTION
**Pull request by tubesoft**
Fixes for the rendition issues: #127, #129, #130, #131.

### CODE REVIEW

**Comment by mdalmau** [comment]
@randalldfloyd : Before I initiate the merge, I wanted to check with you because it's been a long time since the Newton xProc's codebase was updated. @tubesoft has been working on several issues that impact rendition and this pull request aggregates those issues. We thought it would be a good idea to get the site updated before he starts working on the accessibility remediation work. The P5 site is not really known to anyone -- never been launched -- though it's live on production. I believe the dev site gets updated first so @aewingate can test the changes and once she comments that all is good, production can be updated. Does this sound good, Randall? Do we need to get on a schedule for updating dev?

**Comment by mdalmau** [comment]
@randalldfloyd : Wanted to follow-up on this. I won't be able to attend the Newton meeting tomorrow but I can send them an email update about next steps once I hear from you.  Thanks!

**Comment by randalldfloyd** [comment]
@mdalmau @tubesoft 

Here's what I'm hoping to do.  I want to adapt the automated tooling that we use in Digital Collections to enable automatic deployments to the dev instance upon merge of a PR. And it would be totally fine for you and @tubesoft or whoever else to merge remediation PRs as they are created without my approval.  There aren't any other devs to have to worry about here and if something gets broken from a commit we either back it out or push a subsequent fix.

It may take a few rounds of the workflow to get it working right, but if I have to intervene to force a failed update then we won't be any worse off than if I were doing them manually.  Once fixes have been accumulated on dev, we can use the Site Improve plugin to verify that the issues have been fixed and then push them the rest of the way up. Production deployments are always manual, even with Digital Collections, so that would still be me. 

I need a full day or more to get that working in the backend; in the meantime, we can do this PR manually if you want to get a head start on QA in dev for the changes in these commits.

**Comment by randalldfloyd** [comment]
Going to go ahead and merge this.  I'm still getting the automated deployment thing going and merging will help test that, plus it will get in on the dev instances soon for QA ahead of remediation work.

**Comment by mdalmau** [comment]
@aewingate : Chym Dev has. been updated with all the rendition fixes that Takatomo tacked as part of this pull request: https://newton-devel.dlib.indiana.edu. Could you verify that the issues linked above are indeed working correctly in devel. This can be done in the next 2-4 weeks. cc: @wehooper in case he wants to have a look too! Thanks!!

**Comment by aewingate** [comment]
@mdalmau I've checked the four issues in the pull above, and they all appear to work great!

**Comment by mdalmau** [comment]
@tubesoft @randalldfloyd this last newton dev update was vetted by Alex and all issues are working. I know @tubesoft just issued a new pull request with the accessibility issues so maybe we wait to test those on newton dev and then we can do a production update that will cover both of these PRs?

**Comment by randalldfloyd** [comment]
@mdalmau @tubesoft 

Right - the commits from #146 were merged and deployed to devel, so once those have been tested, we can do one deployment to production to deploy the contents of both PRs.

**Pull request merged**
