### PR TITLE
Accessibility issues takatomo

### PR DESCRIPTION
**Pull request by tubesoft**
Fix for the SiteImprove accessibility issues and one rendering issue (#145)

### CODE REVIEW

**Comment by mdalmau** [comment]
I have closed most of the issues that are part of the PR. If testing on newton dev reveals differently, I can re-open. I will now issue a merge request so we can take advantage of the auto update to newton dev. @randalldfloyd : I feel like most of these changes we can really test-test unless we update to production so can we work on scheduling that?

**Comment by randalldfloyd** [comment]
@mdalmau @tubesoft 

If the automated deployment I setup is working correctly, all of these things should be available for testing on the devel instance in some reasonable amount of time after the recent merge.  Even #143 should be testable, just visually inspect the links being generated for search results pagination to verify that they don't accumulate page number references in the parameter list.

**Comment by randalldfloyd** [comment]
@mdalmau @tubesoft 

The devel instance was updated/restarted with this PR merged, and is currently reporting the latest commit level.  So the entire set of changes should be testable there.

**Comment by mdalmau** [comment]
@tubesoft : can you check this on:
http://newton-devel.dlib.indiana.edu -- you'll need to be on the VPN. 

I am not sure I'll know what to look for exactly based on what Randall stated below. 

Thanks!

> @mdalmau @tubesoft
> 
> If the automated deployment I setup is working correctly, all of these things should be available for testing on the devel instance in some reasonable amount of time after the recent merge. Even #143 should be testable, just visually inspect the links being generated for search results pagination to verify that they don't accumulate page number references in the parameter list.

**Pull request merged**
